import { useEffect,useState } from 'react';
import type { DesignSystemVersion,DesignTokens } from '../../shared/schemas/designSystemVersion';
export function contrastRatio(a: string,b: string) {
  const luminance = (hex: string) => { const rgb = [1,3,5].map(i => parseInt(hex.slice(i,i + 2),16) / 255).map(v => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4); return rgb[0] * .2126 + rgb[1] * .7152 + rgb[2] * .0722; };
  const l1 = luminance(a),l2 = luminance(b); return (Math.max(l1,l2) + .05) / (Math.min(l1,l2) + .05);
}
export function DesignWorkspace({ design,busy,onSave,onApprove }: { design: DesignSystemVersion; busy: boolean; onSave: (tokens: DesignTokens) => void; onApprove: () => void }) {
  const [tokens,setTokens] = useState(design.tokens); useEffect(() => setTokens(design.tokens),[design]);
  const dirty = JSON.stringify(tokens) !== JSON.stringify(design.tokens),locked = design.status === 'approved',contrast = contrastRatio(tokens.colors.text,tokens.colors.background);
  return <div className="design-workspace"><div className="section-heading"><div><span className="eyebrow">YOUR NEW VISUAL LANGUAGE · V{design.version}</span><h2>{design.name}</h2><p>Adjust the system. See it come together. Then make it yours.</p></div><span className={`pill ${locked ? 'success' : ''}`}>{locked ? 'Approved & frozen' : 'Draft for your review'}</span></div>
    <section className="design-panel"><div className="panel-heading"><h3>01 / Color palette</h3><span>{contrast.toFixed(2)}:1 text contrast {contrast >= 4.5 ? '✓' : '· needs improvement'}</span></div><div className="swatches">{Object.entries(tokens.colors).map(([name,color]) => <label key={name} className="swatch"><input aria-label={`${name} color`} type="color" value={color} disabled={locked || busy} onChange={event => setTokens({ ...tokens,colors: { ...tokens.colors,[name]: event.target.value } })} /><span>{name}</span><code>{color.toUpperCase()}</code></label>)}</div></section>
    <div className="design-columns"><section className="design-panel"><h3>02 / Typography</h3><label className="field-label">Headings<select value={tokens.typography.headingFont} disabled={locked || busy} onChange={event => setTokens({ ...tokens,typography: { ...tokens.typography,headingFont: event.target.value as DesignTokens['typography']['headingFont'] } })}>{['Manrope','DM Sans','Inter','Space Grotesk','Georgia','Arial','system-ui'].map(font => <option key={font}>{font}</option>)}</select></label><p className="type-specimen" style={{ fontFamily: tokens.typography.headingFont }}>A new<br />perspective.</p><p className="small muted">Body · {tokens.typography.bodyFont} / {tokens.typography.baseSize}px</p><label className="field-label">Corner radius · {tokens.radius}px<input type="range" min="0" max="40" value={tokens.radius} disabled={locked || busy} onChange={event => setTokens({ ...tokens,radius: Number(event.target.value) })} /></label></section>
      <section className="design-panel token-preview" style={{ background: tokens.colors.background,color: tokens.colors.text,fontFamily: tokens.typography.bodyFont }}><span className="eyebrow" style={{ color: tokens.colors.muted }}>03 / LIVE COMPONENT PREVIEW</span><div className="preview-mini-card" style={{ background: tokens.colors.surface,borderColor: tokens.colors.border,borderRadius: tokens.radius }}><span style={{ color: tokens.colors.accent }}>↗</span><h3 style={{ fontFamily: tokens.typography.headingFont }}>Made for a new era.</h3><p style={{ color: tokens.colors.muted }}>Preview copy for reviewing the design system.</p><button type="button" style={{ background: tokens.colors.primary,color: contrastRatio('#ffffff',tokens.colors.primary) >= 4.5 ? '#fff' : '#111',borderRadius: Math.min(tokens.radius,24) }}>Explore the collection <span>↗</span></button></div><div className="spacing-row">{tokens.spacing.slice(0,6).map((size,index) => <div key={index}><span style={{ height: Math.max(4,size),background: tokens.colors.primary }} /><small>{size}</small></div>)}</div></section></div>
    <section className="design-panel"><h3>Why this direction?</h3><div className="rationale-grid">{design.rationale.map((reason,i) => <div key={i}><span className="rationale-number">{String(i + 1).padStart(2,'0')}</span><p>{reason.decision}</p><span className="small muted">Linked to {reason.evidence.length} source references</span></div>)}</div></section>
    {!locked && <div className="approval-bar"><div><strong>Your call. Every time.</strong><p>Approval freezes this version and unlocks page rebuilding.</p></div>{dirty ? <button className="primary" disabled={busy} onClick={() => onSave(tokens)}>Save changes</button> : <button className="primary" disabled={busy || contrast < 4.5} onClick={onApprove}>Approve this design system <span>→</span></button>}</div>}</div>;
}
