import { useEffect,useState } from 'react';
import type { ProjectStateResponse } from './shared/schemas/projectState';
import type { EvidenceManifest } from './shared/schemas/evidenceManifest';
import type { Component,Evaluation } from './shared/schemas/modelResponses';
import type { DesignSystemVersion,DesignTokens } from './shared/schemas/designSystemVersion';
import type { PageSpecification } from './shared/schemas/pageSchema';
import { workflowStages } from './shared/workflow/workflowTypes';
import { api,connectSession,objectUrl } from './app/api/client';
import { fetchProjectState } from './app/api/projectStateClient';
import { ComponentCanvas } from './app/workbench/ComponentCanvas';
import { DesignWorkspace } from './app/workbench/DesignWorkspace';
type Stage = typeof workflowStages[number];
interface Workspace { manifest: EvidenceManifest | null; findings: Evaluation | null; components: Component[]; design: DesignSystemVersion | null; designHash: string | null; pages: { id: string; specification: PageSpecification | null }[]; }
interface Config { ready: boolean; missing: string[]; selectedModel: { value: string }; budget: { limit: number | null }; }
const labels = ['Import','Evaluate','Decompose','Design system','Rebuild','Review','Publish'];
const stageCopy = { import: ['Start with the original.','Every decision starts with real source evidence.'],evaluate: ['Understand before you reinvent.','Evidence-linked findings, with room for your judgment.'],decompose: ['See the pieces. Find the possibilities.','A living map of the interface you’re reimagining.'],design_system: ['Give it a new visual language.','A design system drawn from the original, shaped by you.'],rebuild: ['One page. A whole new perspective.','Build each page with your approved design system.'],review: ['The past meets what’s next.','Compare, inspect, and approve each transformation.'],publish: ['Ready for its next chapter.','Share a frozen release, with the source preserved.'] };
const emptyWorkspace: Workspace = { manifest: null,findings: null,components: [],design: null,designHash: null,pages: [] };
export default function App() {
  const [project,setProject] = useState<string | null>(null),[state,setState] = useState<ProjectStateResponse | null>(null),[workspace,setWorkspace] = useState<Workspace>(emptyWorkspace);
  const [stage,setStage] = useState<Stage>('import'),[pageId,setPageId] = useState(''),[selected,setSelected] = useState<Component | null>(null);
  const [busy,setBusy] = useState(''),[error,setError] = useState(''),[connected,setConnected] = useState(false),[config,setConfig] = useState<Config | null>(null),[settings,setSettings] = useState(false);
  const [preview,setPreview] = useState(''),[compare,setCompare] = useState(50),[mobile,setMobile] = useState(false),[showInspector,setShowInspector] = useState(true);
  async function refresh(id: string) { const [next,data] = await Promise.all([fetchProjectState(id),api<Workspace>(`/api/projects/${id}/workspace`)]); setState(next); setWorkspace(data); setPageId(current => next.pages.some(p => p.id === current) ? current : next.pages[0]?.id ?? ''); }
  useEffect(() => { let active = true; (async () => {
    try { await connectSession(); if (!active) return; setConnected(true); setConfig(await api<Config>('/api/config/status'));
      const projects = await api<{ id: string }[]>('/api/projects'); const saved = localStorage.getItem('reframe-project'); const id = projects.find(p => p.id === saved)?.id ?? projects[0]?.id;
      if (id && active) { setProject(id); await refresh(id); }
    } catch (err) { if (active) setError(err instanceof Error ? err.message : 'The workspace could not connect.'); }
  })(); return () => { active = false; }; },[]);
  async function run(label: string,operation: () => Promise<void>) { setBusy(label); setError(''); try { await connectSession(); await operation(); } catch (err) { setError(err instanceof Error ? err.message : 'This action could not finish.'); } finally { setBusy(''); } }
  async function importSource(file?: File) { await run('Importing source evidence',async () => {
    const created = await api<{ id: string }>('/api/projects','POST',{ name: file ? file.name.replace(/\.zip$/i,'') : 'Space Jam · Reimagined' });
    setProject(created.id); localStorage.setItem('reframe-project',created.id);
    const body = file ? new FormData() : { sourceType: 'sample',sampleId: 'spacejam-1996' }; if (body instanceof FormData && file) body.set('bundle',file);
    try { await api(`/api/projects/${created.id}/imports`,'POST',body); } finally { await refresh(created.id); } setStage('import');
  }); }
  async function generate(action: string,label: string,next: Stage = stage) { if (!project) return; await run(label,async () => { try { await api(`/api/projects/${project}/${action}`,'POST',{}); } finally { await refresh(project); } setStage(next); }); }
  const page = workspace.manifest?.pages.find(page => page.id === pageId),spec = workspace.pages.find(page => page.id === pageId)?.specification;
  useEffect(() => { let active = true; setPreview(''); if (!project || !spec || !['review','rebuild'].includes(stage)) return;
    (async () => { try {
      const result = await api<{ html: string; css: string }>(`/api/projects/${project}/pages/${pageId}/preview`);
      let html = result.html.replace(/<meta http-equiv="Content-Security-Policy"[^>]*>/,'').replace(/<link rel="stylesheet"[^>]*>/,`<style>${result.css}</style>`);
      for (const asset of workspace.manifest?.assets ?? []) {
        const response = await fetch(objectUrl(project,asset.file.objectKey)); if (!response.ok) throw new Error('A preview image is unavailable.');
        const blob = await response.blob(); const dataUrl = await new Promise<string>((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(blob); });
        html = html.replace(new RegExp(`(?:[.][.]/)*assets/${asset.id}[.][a-z]+`,'g'),dataUrl);
      }
      html = html.replace('</head>',`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"></head>`);
      if (active) setPreview(html);
    } catch (err) { if (active) setError(err instanceof Error ? err.message : 'Preview could not load.'); } })(); return () => { active = false; };
  },[project,pageId,spec,stage,workspace.manifest]);
  const aiBlocked = !config?.ready;
  const actionButton = (action: string,label: string,gate: Stage) => <button className="primary" disabled={!!busy || aiBlocked || state?.stages[gate].status === 'Blocked'} onClick={() => generate(action,label)}>{label}<span>↗</span></button>;
  return <div className="studio">
    <header className="topbar"><a className="wordmark" href="/" aria-label="Reframe home"><span className="brandmark">r</span>reframe<span className="wordmark-dot">.</span></a><span className="topbar-divider" /><span className="workspace-label">{state?.project.name ?? 'Modernization studio'}</span><div className="top-actions">{!connected && <a className="secondary" href="/signin-with-chatgpt">Sign in</a>}<button className="quiet" onClick={() => { setProject(null); setState(null); setWorkspace(emptyWorkspace); setStage('import'); }}>＋ New project</button><button className="connection" onClick={() => setSettings(!settings)}><span className={config?.ready ? 'status-dot ready' : 'status-dot'} />{config?.ready ? 'AI connected' : 'Setup needed'}</button><span className="avatar">Y</span></div></header>
    <nav className="workflow-header" aria-label="Modernization workflow">{workflowStages.map((key,index) => <button key={key} className={stage === key ? 'active' : ''} onClick={() => setStage(key)} aria-current={stage === key ? 'step' : undefined}><span className="step-number">{state && ['Completed','Approved','Published'].includes(state.stages[key].status) ? '✓' : String(index + 1).padStart(2,'0')}</span><span>{labels[index]}</span>{state?.stages[key].status === 'Blocked' && <span className="stage-lock">·</span>}</button>)}</nav>
    {settings && <section className="settings-strip"><div><strong>Live AI setup</strong><p>{config?.ready ? `Model: ${config.selectedModel.value}. Application budget: $${config.budget.limit}.` : `Still needed: ${config?.missing.join(' and ') ?? 'connection to the server'}. Add the key as a secret in Reframe’s Sites settings.`}</p></div><a className="secondary" href="https://chatgpt.com/sites" target="_blank" rel="noreferrer">Open Sites settings ↗</a><button className="quiet" onClick={() => run('Checking configuration',async () => setConfig(await api<Config>('/api/config/status')))}>Recheck</button></section>}
    {error && <div className="error-banner" role="alert"><span>{error}</span><button onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}
    {busy && <div className="working-banner" role="status"><span className="spinner" />{busy}… <span>We’ll keep your last saved work until this finishes.</span></div>}
    {!workspace.manifest ? <main className="welcome new-welcome"><div className="welcome-heading"><span className="eyebrow accent">PRESERVE THE SOUL. REIMAGINE THE INTERFACE.</span><h1>Every interface has<br />a next chapter<span>.</span></h1><p>Turn a legacy site into a considered, modern experience.<br />Understand it. Shape its design system. Make it yours.</p></div><div className="import-options"><button className="sample-card" disabled={!connected || !!busy} onClick={() => importSource()}><div className="sample-image"><img src="/samples/home.jpg" alt="Original Space Jam 1996 home page" /><span className="sample-year">1996 → NOW</span></div><div className="sample-copy"><div><span className="eyebrow">THE DEMO COLLECTION</span><h2>Reimagine Space Jam.</h2><p>3 pages · real screenshots · original assets</p></div><span className="circle-arrow">↗</span></div></button><label className="upload-card"><input type="file" accept=".zip" disabled={!connected || !!busy} onChange={event => event.target.files?.[0] && importSource(event.target.files[0])} /><span className="upload-symbol">＋</span><h2>Bring your own history.</h2><p>Upload an evidence bundle with screenshots,<br />source content, links, and image assets.</p><span className="secondary">Choose evidence ZIP</span><small>Up to 3 pages · 20 MB ZIP · <a href="/samples/spacejam-1996.zip" onClick={event => event.stopPropagation()} download>Get the sample format</a></small></label></div><div className="principles"><section><span>01 / UNDERSTAND</span><h2>Start with the evidence.</h2><p>Keep the content, links, and character that make the original yours.</p></section><section><span>02 / REIMAGINE</span><h2>Find a visual language.</h2><p>A site-specific design system, with every decision open for review.</p></section><section><span>03 / MAKE IT REAL</span><h2>Approve. Rebuild. Share.</h2><p>A fresh static site, page by page, with you in control.</p></section></div><footer className="workspace-footer"><span>REFRAME STUDIO</span><span>Built with Forge · Designed around your decisions</span></footer></main> : <div className={`workbench-grid ${showInspector ? '' : 'inspector-hidden'}`}>
      <aside className="page-rail"><div className="rail-heading"><span className="eyebrow">SOURCE PAGES</span><span>{state?.pages.length}</span></div>{workspace.manifest.pages.map(source => <button className={`page-item ${source.id === pageId ? 'selected' : ''}`} key={source.id} onClick={() => { setPageId(source.id); setSelected(null); }}><img src={objectUrl(project!,source.screenshot.objectKey)} alt="" /><strong>{source.title}</strong><span>{source.route}</span><small>{state?.pages.find(p => p.id === source.id)?.approvalState === 'Approved' ? '✓ Approved' : source.id === pageId ? 'Selected page' : 'Source captured'}</small></button>)}<div className="rail-bottom"><span className="small-mark">↗</span><p>The original matters.<br />Keep its story intact.</p></div></aside>
      <main className="workspace-main"><div className="canvas-heading"><div><span className="eyebrow accent">{String(workflowStages.indexOf(stage) + 1).padStart(2,'0')} / {labels[workflowStages.indexOf(stage)].toUpperCase()}</span><h1>{stageCopy[stage][0]}</h1><p>{stageCopy[stage][1]}</p></div><button className="icon-button" aria-label="Toggle inspector" onClick={() => setShowInspector(!showInspector)}>☷</button></div>
      {aiBlocked && !['import','publish'].includes(stage) && <div className="configuration-note"><span>✦</span><div><strong>Your evidence is ready. Live AI needs setup.</strong><p>Add the OpenAI secret and spending limit to generate recommendations.</p></div><button className="quiet" onClick={() => setSettings(true)}>View setup →</button></div>}
      {stage === 'import' && <><div className="evidence-toolbar"><span className="pill success">✓ Source evidence imported</span><span>{workspace.manifest.assets.length} images · {workspace.manifest.pages.reduce((sum,p) => sum + p.links.length,0)} links preserved</span><button className="primary" onClick={() => setStage('evaluate')}>Explore the evaluation →</button></div><div className="source-browser"><div className="browser-bar"><i /><i /><i /><span>{page?.sourceUrl}</span><a href={page?.sourceUrl} target="_blank" rel="noreferrer">↗</a></div><img src={objectUrl(project!,page!.screenshot.objectKey)} alt={`Captured original ${page?.title} page`} /></div><div className="evidence-summary"><div><strong>{page?.regions.length}</strong><span>visible source regions</span></div><div><strong>{page?.links.length}</strong><span>preserved link destinations</span></div><div><strong>{page?.frames.length ? 'Frame-aware' : 'Direct capture'}</strong><span>source provenance retained</span></div></div></>}
      {stage === 'evaluate' && <>{workspace.findings ? <><div className="evaluation-summary"><span className="eyebrow">THE BIG PICTURE</span><h2>{workspace.findings.summary}</h2><div className="inline-actions"><span className="small muted">AI recommendations · linked to captured evidence</span><button className="primary" onClick={() => setStage('decompose')}>Map the components →</button></div></div><div className="findings-grid">{workspace.findings.findings.map(finding => <article className="finding-card" key={finding.id}><div><span className="pill">{finding.category}</span><span className="small muted">{finding.observedVsInferred}</span></div><h3>{finding.title}</h3><p>{finding.description}</p><button className="evidence-link" onClick={() => { setPageId(finding.evidenceRefs[0].pageId); setStage('import'); }}>↗ View source evidence</button></article>)}</div></> : <div className="stage-empty"><span className="stage-illustration">◎</span><h2>A closer look, before a fresh start.</h2><p>Evaluate navigation, readability, structure, and visual consistency.<br />Every finding points back to your captured site.</p>{actionButton('evaluation','Evaluate the site','evaluate')}</div>}</>}
      {stage === 'decompose' && <>{workspace.components.length ? <><div className="canvas-tools"><span>{workspace.components.length} components · drag to explore · lines connect reusable groups</span><button className="primary" onClick={() => setStage('design_system')}>Design the next chapter →</button></div><ComponentCanvas components={workspace.components} manifest={workspace.manifest} projectId={project!} onSelect={component => { setSelected(component); setShowInspector(true); }} /></> : <div className="stage-empty"><span className="stage-illustration">▦</span><h2>Turn the interface into a working canvas.</h2><p>Find the navigation, imagery, content, and repeated patterns.<br />Inspect each component alongside its original screenshot.</p>{actionButton('decomposition','Map existing components','decompose')}</div>}</>}
      {stage === 'design_system' && <>{workspace.design ? <DesignWorkspace design={workspace.design} busy={!!busy} onSave={(tokens: DesignTokens) => run('Saving design changes',async () => { await api(`/api/projects/${project}/design-systems/${workspace.design!.id}/tokens`,'PATCH',{ tokens,expectedHash: workspace.designHash }); await refresh(project!); })} onApprove={() => run('Approving the design system',async () => { await api(`/api/projects/${project}/design-systems/${workspace.design!.id}/approve`,'POST',{ confirm: true,expectedHash: workspace.designHash }); await refresh(project!); setStage('rebuild'); })} /> : <div className="stage-empty"><span className="stage-illustration">✳</span><h2>A new system. Still unmistakably yours.</h2><p>Build a palette, type system, spacing, and component language<br />from the evaluation and the original site’s character.</p>{actionButton('design-systems','Propose a design system','design_system')}</div>}</>}
      {['rebuild','review'].includes(stage) && <><div className="review-toolbar"><div className="segmented"><button className={!mobile ? 'active' : ''} onClick={() => setMobile(false)}>Desktop</button><button className={mobile ? 'active' : ''} onClick={() => setMobile(true)}>Mobile</button></div><span className="small muted">{page?.title} · {spec ? 'Source content preserved' : 'Awaiting rebuild'}</span>{!spec ? actionButton(`pages/${pageId}/rebuild`,'Rebuild this page','rebuild') : <button className="secondary" disabled={!!busy} onClick={() => { setCompare(100); requestAnimationFrame(() => requestAnimationFrame(() => setCompare(0))); }}>✦ Reveal the transformation</button>}</div>{preview ? <><div className={`comparison ${mobile ? 'mobile' : ''}`}><div className="comparison-labels"><span>ORIGINAL</span><span>REIMAGINED</span></div>{!mobile && <img className="comparison-original" src={objectUrl(project!,page!.screenshot.objectKey)} alt="Original captured page" />}<div className="comparison-new" style={{ clipPath: mobile ? 'none' : `inset(0 0 0 ${compare}%)` }}><iframe title={`Reimagined ${page?.title}`} srcDoc={preview} sandbox="" /></div>{!mobile && <div className="comparison-divider" style={{ left: `${compare}%` }}><span>↔</span></div>}</div>{!mobile && <label className="comparison-control"><span>Original</span><input aria-label="Before and after comparison" type="range" min="0" max="100" value={compare} onChange={event => setCompare(Number(event.target.value))} /><span>Reimagined</span></label>}<div className="approval-bar"><div><strong>{state?.pages.find(p => p.id === pageId)?.approvalState === 'Approved' ? 'This page is approved.' : 'Happy with this page?'}</strong><p>{spec?.preservedContent.length} source elements retained · independent page approval</p></div><button className="primary" disabled={!!busy || state?.pages.find(p => p.id === pageId)?.approvalState === 'Approved'} onClick={() => run('Approving this page',async () => { await api(`/api/projects/${project}/pages/${pageId}/approve`,'POST',{ generationId: spec!.id,confirm: true }); await refresh(project!); })}>Approve this page ✓</button></div></> : <div className="stage-empty"><span className="stage-illustration">↗</span><h2>{spec ? 'Preparing the preview…' : 'Your design, brought to life.'}</h2><p>{state?.stages.rebuild.blockedReason ?? 'Rebuild this page, then compare it with the original.'}</p></div>}</>}
      {stage === 'publish' && <div className="publish-card"><span className="stage-illustration">↗</span><span className="eyebrow">A NEW CHAPTER</span><h2>Make the transformation real.</h2><p>{state?.approvals.approvedPageCount} of {state?.approvals.requiredPageCount} pages approved.<br />A release freezes the approved pages and their design system.</p><div className="release-pages">{state?.pages.map(p => <div key={p.id}><span>{p.title}</span><span className="pill">{p.approvalState === 'Approved' ? '✓ Approved' : 'Needs review'}</span></div>)}</div><button className="primary" disabled={!!busy || state?.stages.publish.status === 'Blocked'} onClick={() => generate('releases','Publishing your release','publish')}>Publish the reimagined site ↗</button>{state?.release.latestReleaseId && <a className="secondary" href={`/api/projects/${project}/releases/${state.release.latestReleaseId}/download`}>Download matching ZIP ↓</a>}{state?.release.publicUrl && <a className="secondary" href={state.release.publicUrl} target="_blank" rel="noreferrer">Open published site ↗</a>}<p className="small muted">{state?.stages.publish.blockedReason ?? 'Publication is verified before a live link appears.'}</p></div>}
      </main><aside className={`inspector ${showInspector ? '' : 'hidden'}`}><div className="rail-heading"><span className="eyebrow">{selected ? 'COMPONENT INSPECTOR' : 'CONTEXT & EVIDENCE'}</span><span>↗</span></div>{selected ? <><span className="pill">{selected.semanticRole}</span><h2>{selected.label}</h2><p>{selected.note}</p><dl><dt>Recommendation</dt><dd>{selected.recommendation}</dd><dt>Reusable group</dt><dd>{selected.reusableGroupId}</dd><dt>Evidence</dt><dd>{selected.sourceIds.length} original content references</dd></dl><button className="secondary" onClick={() => { setPageId(selected.sourcePageId); setStage('import'); }}>View original page ↗</button></> : <><h2>{page?.title ?? 'Your project'}</h2><p>Captured source evidence. Every recommendation should be traceable to what is here.</p><dl><dt>Source</dt><dd className="source-url">{page?.sourceUrl}</dd><dt>Viewport</dt><dd>{page?.viewport.width} × {page?.viewport.height}</dd><dt>Capture method</dt><dd>Browser screenshot + source inventory</dd><dt>Design system</dt><dd>{workspace.design?.name ?? 'Created after evaluation'}</dd><dt>Version</dt><dd>{workspace.design ? `v${workspace.design.version} · ${workspace.design.status}` : 'Not generated'}</dd></dl></>}<div className="inspector-note"><span>◈</span><strong>Preservation comes first.</strong><p>Source text, image-map links, assets, and frame provenance stay attached to the project.</p></div>{page?.warnings.length ? <details><summary>Capture notes ({page.warnings.length})</summary>{page.warnings.map((warning,i) => <p className="small" key={i}>{warning}</p>)}</details> : null}<div className="inspector-foot">FORGE-BUILT · HUMAN-APPROVED</div></aside>
    </div>}</div>;
}
